### ISSUE TITLE
teleport error on folia

### ISSUE THREAD

**Issue by PHE-yeji** [Updated-NoCheatPlus/NoCheatPlus#360]
tp PHEyeji ddmod
[21:14:09 INFO]: Teleported PHEyeji to ddmod
[21:14:10 INFO]: [NC+]  PHEyeji 触发检测 SurvivalFly: 可能进行了漏洞飞行 (子模块 vdistsb(103.252/1.35)+ychinc) (VL10190)
[21:14:10 ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Scheduling chunk load off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:288) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:284) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:219) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.world.level.Level.getChunk(Level.java:905) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.world.level.Level.getBlockState(Level.java:1209) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at org.bukkit.craftbukkit.block.CraftBlock.getType(CraftBlock.java:244) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.compat.bukkit.BlockCacheBukkit.fetchTypeId(BlockCacheBukkit.java:53) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.utilities.map.BlockCache.getOrCreateNode(BlockCache.java:317) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.utilities.map.BlockCache.getType(BlockCache.java:379) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.utilities.map.BlockProperties.collectFlagsSimple(BlockProperties.java:4452) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.utilities.location.RichBoundsLocation.collectBlockFlags(RichBoundsLocation.java:1326) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.utilities.location.RichBoundsLocation.collectBlockFlags(RichBoundsLocation.java:1308) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.model.LocationData.setExtraProperties(LocationData.java:92) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.model.MoveData.setWithExtraProperties(MoveData.java:207) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.MovingData.resetPlayerPositions(MovingData.java:589) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.util.AuxMoving.resetPositionsAndMediumProperties(AuxMoving.java:116) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.MovingListener.prepareSetBack(MovingListener.java:1621) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.MovingListener.checkPlayerMove(MovingListener.java:1237) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.MovingListener.onPlayerMove(MovingListener.java:615) ~[NoCheatPlus.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.event.mini.MultiListenerRegistry$AutoListener.onEvent(MultiListenerRegistry.java:82) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.event.mini.MiniListenerNode.onEvent(MiniListenerNode.java:157) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.event.mini.EventRegistryBukkit$4.execute(EventRegistryBukkit.java:124) ~[NoCheatPlus.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-DEV-e6027bd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1618) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:105) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:57) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:85) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1691) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:14:10 ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Scheduling chunk load off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:288) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:284) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:219) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.world.level.Level.getChunk(Level.java:905) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.world.level.Level.getBlockState(Level.java:1209) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at org.bukkit.craftbukkit.block.CraftBlock.getType(CraftBlock.java:244) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.compat.bukkit.BlockCacheBukkit.fetchTypeId(BlockCacheBukkit.java:53) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.utilities.map.BlockCache.getOrCreateNode(BlockCache.java:317) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.utilities.map.BlockCache.getType(BlockCache.java:379) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.utilities.map.BlockProperties.collectFlagsSimple(BlockProperties.java:4452) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.utilities.location.RichBoundsLocation.collectBlockFlags(RichBoundsLocation.java:1326) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.utilities.location.RichBoundsLocation.collectBlockFlags(RichBoundsLocation.java:1308) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.model.LocationData.setExtraProperties(LocationData.java:92) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.model.MoveData.setWithExtraProperties(MoveData.java:207) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.MovingData.resetPlayerPositions(MovingData.java:589) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.util.AuxMoving.resetPositionsAndMediumProperties(AuxMoving.java:116) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.MovingListener.prepareSetBack(MovingListener.java:1621) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.MovingListener.checkPlayerMove(MovingListener.java:1237) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.checks.moving.MovingListener.onPlayerMove(MovingListener.java:615) ~[NoCheatPlus.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.event.mini.MultiListenerRegistry$AutoListener.onEvent(MultiListenerRegistry.java:82) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.event.mini.MiniListenerNode.onEvent(MiniListenerNode.java:157) ~[NoCheatPlus.jar:?]
        at NoCheatPlus.jar/fr.neatmonster.nocheatplus.event.mini.EventRegistryBukkit$4.execute(EventRegistryBukkit.java:124) ~[NoCheatPlus.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-DEV-e6027bd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1618) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:75) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:57) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:85) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1691) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by modpotato** [comment]
same issue here
http://logpaste.com/zvNGY0Jv
