### ISSUE TITLE
Console printing errors nonstop with paper-294

### ISSUE THREAD

**Issue by leomeinel** [Updated-NoCheatPlus/NoCheatPlus#84]
### Full output of /ncp version
[02:33:39] [Server thread/INFO]: ---- Version information ----
[02:33:39] [Server thread/INFO]: #### Server ####
[02:33:39] [Server thread/INFO]: git-Paper-294 ~MC: 1.16.4~
[02:33:39] [Server thread/INFO]:   detected: 1.16.4
[02:33:39] [Server thread/INFO]: #### NoCheatPlus ####
[02:33:39] [Server thread/INFO]: Plugin: 3.17-SNAPSHOT-Updated-b85
[02:33:39] [Server thread/INFO]: MCAccess: 1.13-1.16|? / Bukkit-API
[02:33:39] [Server thread/INFO]: Features:
[02:33:39] [Server thread/INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | BlocksMC1_16 | MCAccessBukkitModern
[02:33:39] [Server thread/INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[02:33:39] [Server thread/INFO]:   defaults: pvpKnockBackVelocity
[02:33:39] [Server thread/INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
[02:33:39] [Server thread/INFO]: Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3 | ViolationFrequency~NCP~ 1.0
[02:33:39] [Server thread/INFO]: #### Related Plugins ####
[02:33:39] [Server thread/INFO]: CompatNoCheatPlus v6.6.5-RC-sMD5NET-b90 | ProtocolLib v4.6.0-SNAPSHOT-b483
### Describe the issue
Console is printing errors nonstop after updating from paper-291 to paper-294
### How to reproduce the issue
Update server to paper-294 and run the server with nocheatplus
### Extra links/Videos (Including debug logs)
log: https://pastebin.com/dNJnMs6T

**Comment by Bobcat00** [comment]
I'm also getting an unhandled exception with Spigot version git-Spigot-a19903d-e1ebdd9 (MC: 1.16.4). This is in a world where all checks are supposedly disabled and the player has the permission nocheckplus.checks, which should exempt him from all checks.

```
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-Updated-b85
MCAccess: 1.13-1.16|? / Bukkit-API
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | BlocksMC1_16 | MCAccessBukkitModern
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.6.0-SNAPSHOT-b482 | ViaVersion v3.2.0
```
 
```
2020-11-26 09:58:06 [ERROR] [NoCheatPlus] Unhandled exception occured in onPacketSending(PacketEvent) for NoCheatPlus
java.lang.IllegalArgumentException: Unable to find getSound in org.bukkit.craftbukkit.v1_16_R3.CraftSound
	at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:280) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.getSoundConverter(BukkitConverters.java:963) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.getSoundEffects(PacketContainer.java:892) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.SoundDistance.isSoundMonitoredLatest(SoundDistance.java:124) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.SoundDistance.isSoundMonitored(SoundDistance.java:139) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.SoundDistance.onPacketSending(SoundDistance.java:154) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:382) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:347) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:184) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:154) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1535) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1508) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.PlayerList.sendPacketNearby(PlayerList.java:950) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.WorldServer.playSound(WorldServer.java:1199) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.Entity.playSound(Entity.java:953) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.Entity.aM(Entity.java:1121) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.Entity.aL(Entity.java:1062) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.Entity.aK(Entity.java:1050) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.EntityItem.tick(EntityItem.java:125) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:663) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.World.a(World.java:718) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:398) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1105) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[custom.jar:git-Spigot-a19903d-e1ebdd9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
2020-11-26 09:58:06 [ERROR] Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutNamedSoundEffect@2917b22c[
    a=net.minecraft.server.v1_16_R3.SoundEffect@2ef14fe
    b=NEUTRAL
    c=-6393
    d=512
    e=6996
    f=0.09657481
    g=0.9975824
  ]
```

**Comment by matt4499** [comment]
can confirm I get this issue too

**Comment by bobhenl** [comment]
Me too
```
[10:25:01 ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketSending(PacketEvent) for NoCheatPlus
java.lang.IllegalArgumentException: Unable to find getSound in org.bukkit.craftbukkit.v1_16_R3.CraftSound
        at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:280) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters.getSoundConverter(BukkitConverters.java:963) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.getSoundEffects(PacketContainer.java:892) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.net.protocollib.SoundDistance.isSoundMonitoredLatest(SoundDistance.java:124) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.net.protocollib.SoundDistance.isSoundMonitored(SoundDistance.java:139) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.net.protocollib.SoundDistance.onPacketSending(SoundDistance.java:154) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:382) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:347) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:291) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:247) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:223) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1696) ~[patched_1.16.4.jar:git-Paper-298]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.playSound(CraftPlayer.java:614) ~[patched_1.16.4.jar:git-Paper-298]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.playSound(CraftPlayer.java:601) ~[patched_1.16.4.jar:git-Paper-298]
        at org.mineacademy.chatcontrol.lib.fo.model.SimpleSound.play(SimpleSound.java:114) ~[?:?]
        at org.mineacademy.chatcontrol.util.Utils.tellMotd(Utils.java:391) ~[?:?]
        at org.mineacademy.chatcontrol.listener.ListenerPlayer.lambda$null$0(ListenerPlayer.java:209) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-298]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-298]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[10:25:01 ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutNamedSoundEffect@12496b7[
    a=net.minecraft.server.v1_16_R3.SoundEffect@4acf51b4
    b=MASTER
    c=102
    d=1120
    e=158
    f=1.0
    g=0.1
  ]
```

**Comment by Diamondback88** [comment]
Can confirm I get this error too

**Comment by compieter-gh** [comment]
Can confirm i have this issue also.

**Comment by cavallium** [comment]
This problem is not related to NCP. It's a bug in ProtocolLib:

https://github.com/dmulloy2/ProtocolLib/issues/1023

**Comment by AoElite** [comment]
You can fix it by disabling sounddistance in the config.yml
``` 
   sounddistance:
      active: false
```

**Comment by CaptainObvious0** [comment]
Please update ProtocolLib
