### ISSUE TITLE
Error on server startup

### ISSUE THREAD

**Issue by yunusemregul** [Updated-NoCheatPlus/NoCheatPlus#94]
### Full output of /ncp version 
The plugin doesn't even work so I can't use /ncp version

### Describe the issue
Gives errors on server startup

### How to reproduce the issue
Download spigot-1.16.4.jar, start a clean server put NoCheatPlus.jar in plugins folder

### Extra links/Videos (Including debug logs)
Error:
```
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ExceptionInInitializerError
	at fr.neatmonster.nocheatplus.config.DefaultConfig.<init>(DefaultConfig.java:201) ~[?:?]
	at fr.neatmonster.nocheatplus.worlds.WorldDataManager.createDefaultWorldData(WorldDataManager.java:202) ~[?:?]
	at fr.neatmonster.nocheatplus.worlds.WorldDataManager.<init>(WorldDataManager.java:142) ~[?:?]
	at fr.neatmonster.nocheatplus.NoCheatPlus.<init>(NoCheatPlus.java:190) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	... 7 more
Caused by: java.lang.NullPointerException: Material not present: diamond_shovel, diamond_spade
	at fr.neatmonster.nocheatplus.compat.BridgeMaterial.getFirstNotNull(BridgeMaterial.java:128) ~[?:?]
	at fr.neatmonster.nocheatplus.compat.BridgeMaterial.<clinit>(BridgeMaterial.java:165) ~[?:?]
	at fr.neatmonster.nocheatplus.config.DefaultConfig.<init>(DefaultConfig.java:201) ~[?:?]
	at fr.neatmonster.nocheatplus.worlds.WorldDataManager.createDefaultWorldData(WorldDataManager.java:202) ~[?:?]
	at fr.neatmonster.nocheatplus.worlds.WorldDataManager.<init>(WorldDataManager.java:142) ~[?:?]
	at fr.neatmonster.nocheatplus.NoCheatPlus.<init>(NoCheatPlus.java:190) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	... 7 more
```
Whole server log:
```
[00:42:34 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:42:34 INFO]: Reloading ResourceManager: Default, bukkit
[00:42:34 INFO]: Loaded 7 recipes
[00:42:36 INFO]: Starting minecraft server version 1.16.4
[00:42:36 INFO]: Loading properties
[00:42:36 INFO]: This server is running CraftBukkit version git-Spigot-a93cbb1-7a6c3c9 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[00:42:36 INFO]: Using 4 threads for Netty based IO
[00:42:37 INFO]: Server Ping Player Sample Count: 12
[00:42:37 INFO]: Debug logging is disabled
[00:42:37 INFO]: Default game type: SURVIVAL
[00:42:37 INFO]: Generating keypair
[00:42:37 INFO]: Starting Minecraft server on *:25565
[00:42:37 INFO]: Using default channel type
[00:42:38 ERROR]: Could not load 'plugins\NoCheatPlus.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ExceptionInInitializerError
	at fr.neatmonster.nocheatplus.config.DefaultConfig.<init>(DefaultConfig.java:201) ~[?:?]
	at fr.neatmonster.nocheatplus.worlds.WorldDataManager.createDefaultWorldData(WorldDataManager.java:202) ~[?:?]
	at fr.neatmonster.nocheatplus.worlds.WorldDataManager.<init>(WorldDataManager.java:142) ~[?:?]
	at fr.neatmonster.nocheatplus.NoCheatPlus.<init>(NoCheatPlus.java:190) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	... 7 more
Caused by: java.lang.NullPointerException: Material not present: diamond_shovel, diamond_spade
	at fr.neatmonster.nocheatplus.compat.BridgeMaterial.getFirstNotNull(BridgeMaterial.java:128) ~[?:?]
	at fr.neatmonster.nocheatplus.compat.BridgeMaterial.<clinit>(BridgeMaterial.java:165) ~[?:?]
	at fr.neatmonster.nocheatplus.config.DefaultConfig.<init>(DefaultConfig.java:201) ~[?:?]
	at fr.neatmonster.nocheatplus.worlds.WorldDataManager.createDefaultWorldData(WorldDataManager.java:202) ~[?:?]
	at fr.neatmonster.nocheatplus.worlds.WorldDataManager.<init>(WorldDataManager.java:142) ~[?:?]
	at fr.neatmonster.nocheatplus.NoCheatPlus.<init>(NoCheatPlus.java:190) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
	... 7 more
[00:42:38 INFO]: Preparing level "world"
[00:42:38 INFO]: -------- World Settings For [world] --------
[00:42:38 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[00:42:38 INFO]: Item Merge Radius: 2.5
[00:42:38 INFO]: Item Despawn Rate: 6000
[00:42:38 INFO]: View Distance: 10
[00:42:38 INFO]: Zombie Aggressive Towards Villager: true
[00:42:38 INFO]: Nerfing mobs spawned from spawners: false
[00:42:38 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[00:42:38 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[00:42:38 INFO]: Max TNT Explosions: 100
[00:42:38 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[00:42:38 INFO]: Experience Merge Radius: 3.0
[00:42:38 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[00:42:38 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[00:42:38 INFO]: Cactus Growth Modifier: 100%
[00:42:38 INFO]: Cane Growth Modifier: 100%
[00:42:38 INFO]: Melon Growth Modifier: 100%
[00:42:38 INFO]: Mushroom Growth Modifier: 100%
[00:42:38 INFO]: Pumpkin Growth Modifier: 100%
[00:42:38 INFO]: Sapling Growth Modifier: 100%
[00:42:38 INFO]: Beetroot Growth Modifier: 100%
[00:42:38 INFO]: Carrot Growth Modifier: 100%
[00:42:38 INFO]: Potato Growth Modifier: 100%
[00:42:38 INFO]: Wheat Growth Modifier: 100%
[00:42:38 INFO]: NetherWart Growth Modifier: 100%
[00:42:38 INFO]: Vine Growth Modifier: 100%
[00:42:38 INFO]: Cocoa Growth Modifier: 100%
[00:42:38 INFO]: Bamboo Growth Modifier: 100%
[00:42:38 INFO]: SweetBerry Growth Modifier: 100%
[00:42:38 INFO]: Kelp Growth Modifier: 100%
[00:42:38 INFO]: Mob Spawn Range: 6
[00:42:38 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[00:42:38 INFO]: -------- World Settings For [world_nether] --------
[00:42:38 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[00:42:38 INFO]: Item Merge Radius: 2.5
[00:42:38 INFO]: Item Despawn Rate: 6000
[00:42:38 INFO]: View Distance: 10
[00:42:38 INFO]: Zombie Aggressive Towards Villager: true
[00:42:38 INFO]: Nerfing mobs spawned from spawners: false
[00:42:38 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[00:42:38 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[00:42:38 INFO]: Max TNT Explosions: 100
[00:42:38 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[00:42:38 INFO]: Experience Merge Radius: 3.0
[00:42:38 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[00:42:38 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[00:42:38 INFO]: Cactus Growth Modifier: 100%
[00:42:38 INFO]: Cane Growth Modifier: 100%
[00:42:38 INFO]: Melon Growth Modifier: 100%
[00:42:38 INFO]: Mushroom Growth Modifier: 100%
[00:42:38 INFO]: Pumpkin Growth Modifier: 100%
[00:42:38 INFO]: Sapling Growth Modifier: 100%
[00:42:38 INFO]: Beetroot Growth Modifier: 100%
[00:42:38 INFO]: Carrot Growth Modifier: 100%
[00:42:38 INFO]: Potato Growth Modifier: 100%
[00:42:38 INFO]: Wheat Growth Modifier: 100%
[00:42:38 INFO]: NetherWart Growth Modifier: 100%
[00:42:38 INFO]: Vine Growth Modifier: 100%
[00:42:38 INFO]: Cocoa Growth Modifier: 100%
[00:42:38 INFO]: Bamboo Growth Modifier: 100%
[00:42:38 INFO]: SweetBerry Growth Modifier: 100%
[00:42:38 INFO]: Kelp Growth Modifier: 100%
[00:42:38 INFO]: Mob Spawn Range: 6
[00:42:38 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[00:42:38 INFO]: -------- World Settings For [world_the_end] --------
[00:42:38 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[00:42:38 INFO]: Item Merge Radius: 2.5
[00:42:38 INFO]: Item Despawn Rate: 6000
[00:42:38 INFO]: View Distance: 10
[00:42:38 INFO]: Zombie Aggressive Towards Villager: true
[00:42:38 INFO]: Nerfing mobs spawned from spawners: false
[00:42:38 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[00:42:38 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[00:42:38 INFO]: Max TNT Explosions: 100
[00:42:38 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[00:42:38 INFO]: Experience Merge Radius: 3.0
[00:42:38 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[00:42:38 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[00:42:38 INFO]: Cactus Growth Modifier: 100%
[00:42:38 INFO]: Cane Growth Modifier: 100%
[00:42:38 INFO]: Melon Growth Modifier: 100%
[00:42:38 INFO]: Mushroom Growth Modifier: 100%
[00:42:38 INFO]: Pumpkin Growth Modifier: 100%
[00:42:38 INFO]: Sapling Growth Modifier: 100%
[00:42:38 INFO]: Beetroot Growth Modifier: 100%
[00:42:38 INFO]: Carrot Growth Modifier: 100%
[00:42:38 INFO]: Potato Growth Modifier: 100%
[00:42:38 INFO]: Wheat Growth Modifier: 100%
[00:42:38 INFO]: NetherWart Growth Modifier: 100%
[00:42:38 INFO]: Vine Growth Modifier: 100%
[00:42:38 INFO]: Cocoa Growth Modifier: 100%
[00:42:38 INFO]: Bamboo Growth Modifier: 100%
[00:42:38 INFO]: SweetBerry Growth Modifier: 100%
[00:42:38 INFO]: Kelp Growth Modifier: 100%
[00:42:38 INFO]: Mob Spawn Range: 6
[00:42:38 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[00:42:38 INFO]: Preparing start region for dimension minecraft:overworld
[00:42:39 INFO]: Preparing spawn area: 0%
[00:42:39 INFO]: Preparing spawn area: 0%
[00:42:39 INFO]: Preparing spawn area: 0%
[00:42:42 INFO]: Preparing spawn area: 83%
[00:42:42 INFO]: Preparing spawn area: 83%
[00:42:42 INFO]: Preparing spawn area: 83%
[00:42:42 INFO]: Preparing spawn area: 83%
[00:42:42 INFO]: Preparing spawn area: 83%
[00:42:42 INFO]: Preparing spawn area: 83%
[00:42:43 INFO]: Preparing spawn area: 83%
[00:42:43 INFO]: Preparing spawn area: 87%
[00:42:44 INFO]: Preparing spawn area: 91%
[00:42:44 INFO]: Time elapsed: 5827 ms
[00:42:44 INFO]: Preparing start region for dimension minecraft:the_nether
[00:42:45 INFO]: Preparing spawn area: 0%
[00:42:45 INFO]: Preparing spawn area: 83%
[00:42:45 INFO]: Preparing spawn area: 83%
[00:42:46 INFO]: Preparing spawn area: 87%
[00:42:46 INFO]: Preparing spawn area: 99%
[00:42:46 INFO]: Time elapsed: 2024 ms
[00:42:46 INFO]: Preparing start region for dimension minecraft:the_end
[00:42:47 INFO]: Preparing spawn area: 0%
[00:42:47 INFO]: Preparing spawn area: 87%
[00:42:47 INFO]: Time elapsed: 591 ms
[00:42:47 INFO]: Server permissions file permissions.yml is empty, ignoring it
[00:42:47 INFO]: Done (8.697s)! For help, type "help"
```

**Comment by nuage00** [comment]
I have the same issue.

**Comment by xaw3ep** [comment]
Done!
